# how many distinct terms are in the sequence generated by a^b for 2 <= a, b <= 100?
terms = []
(2..100).each do |a|
	(2..100).each do |b|
		terms << a**b
	end
	puts "done #{a}"
end
puts terms.uniq.size